---
- hosts: centos
  remote_user: sgrosu
  tasks:
    - name: test php installation
      template: 
        src: templates/http_var.j2
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
      become: yes