---
- hosts: ubuntu
  remote_user: sgrosu
  #become_user: sgrosu
  tasks:
  - name: install apache2
    apt:
      name: apache2
      state: present
    become: yes
  - name: start apache2
    service:
      name: apache2
      state: started
      enabled: True
    become: yes
  - name: add PHP PPA repository
    apt_repository:
      repo: 'ppa:ondrej/php'
    become: yes
  - name: install PHP 5.6 packages
    apt:
      name: '{{ item }}'
      state: present
      #update_cache: yes
    become: yes
    with_items:
      - php5.6
      - php5.6-mbstring
      - php5.6-mcrypt
      - php5.6-mysql 
      - php5.6-xml
      - php5.6-cli
      - php5.6-common
  - name: restart httpd
    service:
      name: apache2
      state: restarted
    become: yes
  


