---
- hosts: centos
  remote_user: sgrosu
  #become_user: sgrosu
  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: present
    become: yes
  - name: install PHP packages
    yum:
      name: '{{ item }}'
      state: present
    become: yes
    with_items:
      - php
      - php-common
      - php-opcache
      - php-cli
      - php-mysql
      - php-pear
  - name: start httpd
    service:
      name: httpd
      state: started
      enabled: True
    become: yes
