---
- hosts: centos
  remote_user: sgrosu
  #become_user: sgrosu
  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: present
    become: yes
  - name: start httpd
    service:
      name: httpd
      state: started
      enabled: True
    become: yes
