---
- hosts: all
  remote_user: sgrosu
  tasks:
    - name: ensure the MOTD file is present and updated
      template:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644
      become: yes