---
- hosts: centos
  remote_user: sgrosu
  tasks:
  - name: Ensure ansible username exists
    user: 
      name: ansible
      state: present
      comment: Ansible
      groups: wheel
      append: yes
    become: yes
  - name: Copy user's SSH key to the machine
    authorized_key: 
      user: ansible
      state: present
      key: "{{ lookup('file', '/home/sgrosu/ansible_key/id_rsa.pub') }}"
      #path: /home/ansible/.ssh/authorized_keys
      #manage_dir: False
    become: yes
  - name: Ensure the user is sudoer with no password
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^ansible ALL\='
      line: 'ansible ALL=(ALL) NOPASSWD:ALL'
      validate: 'visudo -cf %s'
    become: yes